export const charmander = {
  image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/4.png',
  name: 'charmander',
  attacks: ['blaze', 'solar power'],
  evolution: 'charmeleon',
  heightType: 'm',
  height: 0.6,
  weightType: 'kg',
  weight: '8.5',
  baseHP: 39,
  attack: 52,
  attackSpecial: 60,
  defense: 43,
  defenseSpecial: 50,
  speed: 65,
  type: 'fire',
};